### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by akinnane**

### CODE REVIEW

**Comment by danjoneslf** [comment]
The environment variables are inside a docker container and are defaulted to an empty string if they're not present in the parent shell. The point is that if you run `make test` without `aws-vault` the docker container has no aws creds instead of empty ones.

**Comment by danjoneslf** [comment]
The broken tests are broken because you've got rid of the code that removes the default empty env vars.

**Comment by akinnane** [comment]
I guess the problem with those tests is that the is some resident state that changes the result of the tests. There is state transferred from `test_get_set_options` to `test_read_json` and then to `test_read_s3`. 

`test_read_s3` will pass when run without a valid AWS key if the previous two tests are run.  `test_read_json` is also dependant on `test_get_set_options` to be able to pass.
Screenshot from 2019-10-03 12-21-17
Screenshot from 2019-10-03 12-21-07
Screenshot from 2019-10-03 12-19-15

**Comment by akinnane** [comment]
Screenshot from 2019-10-03 12-21-17
Screenshot from 2019-10-03 12-21-07

**Comment by akinnane** [comment]
Screenshot from 2019-10-03 12-21-17
Screenshot from 2019-10-03 12-21-07

**Comment by akinnane** [comment]
Screenshot from 2019-10-03 12-26-33

**Comment by akinnane** [comment]
I've done the following:

**Comment by akinnane** [comment]
I've added skips for the tests that break when run randomly.

**Pull request merged**
